// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxmoglnzzbggrbriuxjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bW9nbG56emJnZ3Jicml1eGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEwNjQsImV4cCI6MjA2NTQ2NzA2NH0.9Oy0SPSNWuPMze6e12L_deHGDeDeek5BNjoDXDfQzbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);